

```{r}
library(data.table)
Sys.which("R")
.libPaths()
```


```{r}
simulate_data <- function(n, d = 5, sigma = 1, setup = c("A", "B", "C", "D")) {
  setup <- match.arg(setup)
  
  # Helper functions
  trimo <- function(x) pmin(pmax(x, 0.1), 0.9)  # trim to [0.1, 0.9]
  
  if (setup == "A") {
    # Friedman baseline
    X <- matrix(runif(n * d, 0, 1), n, d)
    b_fun <- function(x) sin(pi * x[,1] * x[,2]) + 2 * (x[,3] - 0.5)^2 + x[,4] + 0.5 * x[,5]
    e_fun <- function(x) trimo(1 * sin(pi * x[,1] * x[,2]))
    tau_fun <- function(x) (x[,1] + x[,2]) / 2
  }
  
  if (setup == "B") {
    X <- matrix(rnorm(n * d), n, d)
    b_fun <- function(x) pmax(x[,1] + x[,2], x[,3], 0) + pmax(x[,4] + x[,5], 0)
    e_fun <- function(x) rep(0.5, n)  # randomized trial
    tau_fun <- function(x) x[,1] + log(1 + exp(x[,2]))
  }
  
  if (setup == "C") {
    X <- matrix(rnorm(n * d), n, d)
    b_fun <- function(x) 2 * log(1 + exp(x[,1] + x[,2] + x[,3]))
    e_fun <- function(x) 1 / (1 + exp(-(x[,2] + x[,3])))
    tau_fun <- function(x) rep(1, n)  # constant treatment effect
  }
  
  if (setup == "D") {
    X <- matrix(rnorm(n * d), n, d)
    b_fun <- function(x) (pmax(x[,1] + x[,2] + x[,3], 0) + 
                          pmax(x[,4] + x[,5], 0)) / 2
    e_fun <- function(x) 1 / (1 + exp(-x[,1] - x[,2]))
    tau_fun <- function(x) pmax(x[,1] + x[,2] + x[,3], 0) - 
                          pmax(x[,4] + x[,5], 0)
  }
  
  # Generate data
  e <- e_fun(X)
  W <- rbinom(n, 1, e)
  eps <- rnorm(n)
  Y <- b_fun(X) + (W - 0.5) * tau_fun(X) + sigma * eps
  
  data.frame(Y = Y, W = W, X)
}


set.seed(123)

# Setup A: difficult nuisance, easy tau
datA <- simulate_data(n = 2000, setup = "A")

# Setup B: randomized trial
datB <- simulate_data(n = 2000, setup = "B")

# Setup C: strong confounding, easy e(x)
datC <- simulate_data(n = 2000, setup = "C")

# Setup D: unrelated arms
datD <- simulate_data(n = 2000, setup = "D")

head(datA)





```



```{r}




```
